"""Tests for systemd unit content generated by deploy/deploy-services.sh.

These tests validate the structure and properties of the generated unit files
without actually writing to system directories or running systemctl.
"""

import os
import textwrap


# ── Helpers ────────────────────────────────────────────────────────────

def _generate_server_unit(venv_python, project_dir):
    """Generate stt-server.service content (mirrors deploy script template)."""
    return textwrap.dedent(f"""\
    [Unit]
    Description=Speech-to-text server
    After=network.target

    [Service]
    ExecStart={venv_python} {project_dir}/servers/speech_to_text_server.py
    Restart=always
    RestartSec=5

    [Install]
    WantedBy=default.target
    """)


def _generate_keylistener_unit(system_python, project_dir):
    """Generate stt-keylistener.service content (mirrors deploy script template)."""
    return textwrap.dedent(f"""\
    [Unit]
    Description=Speech-to-text key listener
    Wants=graphical.target
    After=graphical.target

    [Service]
    ExecStart={system_python} {project_dir}/servers/key_listener.py
    Restart=always
    RestartSec=5

    [Install]
    WantedBy=multi-user.target
    """)


# ── stt-server.service ─────────────────────────────────────────────────

class TestServerUnit:
    """Validate the user-level stt-server.service unit."""

    def test_has_restart_always(self):
        content = _generate_server_unit("/home/user/.venv/bin/python3", "/opt/stt")
        assert "Restart=always" in content

    def test_has_restart_sec(self):
        content = _generate_server_unit("/home/user/.venv/bin/python3", "/opt/stt")
        assert "RestartSec=5" in content

    def test_wanted_by_default_target(self):
        content = _generate_server_unit("/home/user/.venv/bin/python3", "/opt/stt")
        assert "WantedBy=default.target" in content

    def test_after_network_target(self):
        content = _generate_server_unit("/home/user/.venv/bin/python3", "/opt/stt")
        assert "After=network.target" in content

    def test_exec_start_points_to_server_script(self):
        content = _generate_server_unit("/home/user/.venv/bin/python3", "/opt/stt")
        assert "ExecStart=/home/user/.venv/bin/python3 /opt/stt/servers/speech_to_text_server.py" in content

    def test_is_valid_unit_section_structure(self):
        content = _generate_server_unit("/home/user/.venv/bin/python3", "/opt/stt")
        assert "[Unit]" in content
        assert "[Service]" in content
        assert "[Install]" in content


# ── stt-keylistener.service ────────────────────────────────────────────

class TestKeyListenerUnit:
    """Validate the system-level stt-keylistener.service unit."""

    def test_has_restart_always(self):
        content = _generate_keylistener_unit("/usr/bin/python3", "/opt/stt")
        assert "Restart=always" in content

    def test_has_restart_sec(self):
        content = _generate_keylistener_unit("/usr/bin/python3", "/opt/stt")
        assert "RestartSec=5" in content

    def test_wanted_by_multi_user_target(self):
        content = _generate_keylistener_unit("/usr/bin/python3", "/opt/stt")
        assert "WantedBy=multi-user.target" in content

    def test_waits_for_graphical_session(self):
        """Key listener needs DISPLAY/XAUTHORITY — must start after graphical session."""
        content = _generate_keylistener_unit("/usr/bin/python3", "/opt/stt")
        assert "Wants=graphical.target" in content
        assert "After=graphical.target" in content

    def test_no_multi_user_after(self):
        """Key listener should wait for graphical.target, not multi-user.target."""
        content = _generate_keylistener_unit("/usr/bin/python3", "/opt/stt")
        assert "After=multi-user.target" not in content

    def test_exec_start_points_to_key_listener_script(self):
        content = _generate_keylistener_unit("/usr/bin/python3", "/opt/stt")
        assert "ExecStart=/usr/bin/python3 /opt/stt/servers/key_listener.py" in content

    def test_is_valid_unit_section_structure(self):
        content = _generate_keylistener_unit("/usr/bin/python3", "/opt/stt")
        assert "[Unit]" in content
        assert "[Service]" in content
        assert "[Install]" in content


# ── Both services survive reboot ───────────────────────────────────────

class TestSurviveReboot:
    """Both units must be enabled to start on boot and survive crashes."""

    def test_server_enabled_via_wantedby(self):
        content = _generate_server_unit("/home/user/.venv/bin/python3", "/opt/stt")
        assert "WantedBy=default.target" in content

    def test_keylistener_enabled_via_wantedby(self):
        content = _generate_keylistener_unit("/usr/bin/python3", "/opt/stt")
        assert "WantedBy=multi-user.target" in content

    def test_both_have_restart_always(self):
        server = _generate_server_unit("/home/user/.venv/bin/python3", "/opt/stt")
        keylistener = _generate_keylistener_unit("/usr/bin/python3", "/opt/stt")
        assert "Restart=always" in server
        assert "Restart=always" in keylistener
